# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${GIN_PORT}:${GIN_PORT}"
    restart: unless-stopped
    depends_on:
      - redis
    links:
      - redis

  # https://docs.docker.com/compose/gettingstarted/#step-3-define-services-in-a-compose-file
  redis:
    image: "redis:alpine"